name: Staging Orchestration

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write
  actions: write
  pull-requests: write

jobs:
  ci:
    uses: "./.github/workflows/test.yml"
    secrets: inherit
  build_cd:
    needs: [ci]
    uses: "./.github/workflows/cd-build-and-release.yml"
    with:
      commitMessages: ${{ github.event.head_commit.message }}
    secrets: inherit
